camel:
  springboot:
    main-run-controller: true

kafka:
  broker1:
    host: 'localhost:9092'
  broker2:
    host: 'localhost:19092'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sessions?WriteBatchedInsert=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 25