{
 "title": "App monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Message received count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "app_message_received_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Message failed count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "app_message_failed_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Message timer max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(app_message_timer_seconds_sum[5m]) / rate(app_message_timer_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message success count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "app_message_success_total", "legendFormat": "__auto" }
   ]
  }
 ]
}